### ISSUE TITLE
Bill of Materials / Schematic mismatch

### ISSUE THREAD

**Issue by AHurnell** [particle-iot/app-notes#1]
Thanks for this helpful board design, just thought I would try to improve it.

The bill of materials for the basic SoM design includes a 0.1uF capacitor which I cannot see in the schematic or brd file. Suggest removing it from the Bill of materials.

The bill of materials also doesn't include the battery connector. The line I would add for that in the BOM table is...
1 |
Battery connector JST_2PIN-THM (JST_2PIN) |
https://www.digikey.com/products/en?mpart=S2B-PH-K-S%28LF%29%28SN%29&v=455 |

**Comment by rickkas7** [comment]
Thank you for pointing that out. I removed the 0.1uF capacitor and added the JST-PH connector to the BOM.
